#!/usr/bin/env bash
# Copyright (C) 2019-2020 LinkedData.Center - All Rights Reserved
# Permission to copy and modify is granted under the MIT license

if [ -z "${JETTY_BASE}" ]; then
	>&2 echo "No JETTY_BASE found, is JETTY installed?"
	exit 2
fi

#### config defaults #########
_FOREGROUND=1
_READONLY=0
_SIZE=micro
_LOGDIR="${SDAAS_STORE_LOG:-"$JETTY_BASE"}"
_STORENAME="${SDAAS_STORE_NAME:-rdfStore}"
_ETC="${SDAAS_STORE_ETC:-"/etc/$_STORENAME"}"



function USAGE {
	>&2 cat <<-EOT
		Smart Data as a Service (SDaaS) knowledge graph engine
		Copyright (C) 2018-2024 http://linkeddata.center/
			
		startup options:
		
		-d, --background
			execute the platform as a daemon
		
		--readonly
		   disallow mutations in graph database
		   
		--size micro|small|medium|large|xlarge|xxlarge|custom
	EOT
	exit 1
}


### Parse command line options

while [ "$#" -gt 0 ]; do
	case "$1" in
	    -d|--background)
	    	_FOREGROUND=0
            shift
	    	;;
		--readonly)
	    	_READONLY=1
            shift
	    	;;
	    --size)
			_SIZE="${2-micro}"
	    	shift 2
	    	;;
        --)
            shift
            break
        	;;
	    *)
	        USAGE
	    	;;
	esac
done

## $_SIZE is used to set JAVA_OPTS configurations use "--size custom" to let JAVA_OPTS untouched
case "$_SIZE" in
    micro)
    	JAVA_OPTS="-server -Xmx256m -Djava.awt.headless=true"
    	;;
    small)
    	JAVA_OPTS="-server -Xmx1g -Djava.awt.headless=true"
    	;;
    medium)
    	JAVA_OPTS="-server -XX:+UseG1GC -Xmx2g -Djava.awt.headless=true "
    	;;
	large)
    	JAVA_OPTS="-server -XX:+UseG1GC -Xmx4g -Djava.awt.headless=true"
    	;;
	xlarge)
    	JAVA_OPTS="-server -XX:+UseG1GC -Xmx8g -Djava.awt.headless=true"
    	;;
	xxlarge)
    	JAVA_OPTS="-server -XX:+UseG1GC -Xmx16g -Djava.awt.headless=true"
    	;;
    custom)
    	;;
    *)
    	USAGE
    	;;
esac


startupMsg="SDaaS knowledge graph engine starting using $_SIZE memory footprint"

if [  $_READONLY -eq 1 ]; then 
	sed 's/__READONLY__/true/' "${SDAAS_STORE_ETC}/readonly-template.xml"  > "${JETTY_BASE}/readonly-override.xml"
	startupMsg="READONLY - $startupMsg"
else
	sed 's/__READONLY__/false/' "${SDAAS_STORE_ETC}/readonly-template.xml" > "${JETTY_BASE}/readonly-override.xml"
fi


_STARTUP_CMD="java ${JAVA_OPTS:-''} -jar "${JETTY_HOME}/start.jar" STOP.PORT=28282 STOP.KEY=secret"
if [ $_FOREGROUND -eq 1 ]; then
	echo "${startupMsg}. Press ctrl-c to stop."
	cd "${JETTY_BASE}" &&  $_STARTUP_CMD
else
	echo "$startupMsg as daemon."
	cd "${JETTY_BASE}" &&  $_STARTUP_CMD >> "${_LOGDIR}/${_STORENAME}.log"  2>&1 &
fi