#!/usr/bin/env bash
# Copyright (C) 2019-2020 LinkedData.Center - All Rights Reserved
# Permission to copy and modify is granted under the MIT license

cd ${JETTY_HOME} &&  jetty java -jar /usr/local/jetty/start.jar \
	STOP.PORT=28282 STOP.KEY=secret --stop


echo "SDaaS engine stopped"
