#!/usr/bin/env bash
# Copyright (C) 2019 LinkedData.Center - All Rights Reserved
# Permission to copy and modify is granted under the MIT license


function USAGE {
	>&2 cat <<-EOT
		Smart Data as a Service (SDaaS) platform community edition
		Copyright (C) 2018-2020 http://linkeddata.center/
			
		startup options:
		
		--foreground
			execute the platform in foreground
		
		--readonly
		   disallow mutations in graph database
	EOT
	exit 1
}


### Parse command line options
FOREGROUND=0
READONLY=0
while [ "$#" -gt 0 ]; do
	case "$1" in
	    --foreground)
	    	FOREGROUND=1
            shift
	    	;;
		--readonly)
	    	READONLY=1
            shift
	    	;;
        --)
            break
        ;;
	    *)
	        USAGE
	    ;;
	esac
	shift
done

case "${GDAAS_SIZE:-micro}" in
    micro)
    	JAVA_OPTS="-server -Xmx1g -Djava.awt.headless=true"
    	;;
    small)
    	JAVA_OPTS="-server -Xmx2g -Djava.awt.headless=true"
    	;;
    medium)
    	JAVA_OPTS="-server -Xmx4g -Djava.awt.headless=true"
    	;;
	large)
    	JAVA_OPTS="-server -Xmx8g -Djava.awt.headless=true"
    	;;
	xlarge)
    	JAVA_OPTS="-server -Xmx16g -Djava.awt.headless=true"
    	;;
    *)
        >&2 echo ERROR: UNSUPPORTED GDAAS_SIZE $GDAAS_SIZE
        exit 2
    ;;
esac




if [  $READONLY -eq 1 ]; then 
	cp ${JETTY_BASE}/readonly-web.xml ${JETTY_BASE}/webapps/sdaas/WEB-INF/web.xml
else
	cp ${JETTY_BASE}/writable-web.xml ${JETTY_BASE}/webapps/sdaas/WEB-INF/web.xml
fi

STARTUP_CMD="java -jar /usr/local/jetty/start.jar STOP.PORT=28282 STOP.KEY=secret"

echo -n "SDaaS knowledge graph engine starting..."

if [ $FOREGROUND -eq 1 ]; then
	echo "Press ctrl-c to stop."
	cd ${JETTY_BASE} &&  $STARTUP_CMD
else
	echo "as daemon (10 sec pre-warmup)"
	cd ${JETTY_BASE} &&  $STARTUP_CMD &
	sleep 10
fi